### ISSUE TITLE
library server error

### ISSUE THREAD

**Issue by bradjc** [lab11/accessors#35]
```
2015-05-29 18:26:12 nuclear tornado.application[15668] ERROR Uncaught exception POST /dev/upload (127.0.0.1)
HTTPServerRequest(protocol='http', host='accessors.io', method='POST', uri='/dev/upload', version='HTTP/1.0', remote_ip='127.0.0.1', headers={'X-Forwarded-Proto': 'http', 'Content-Length': '7150', 'Host': 'accessors.io', 'Connection': 'close', 'X-Forwarded-For': '136.152.142.36', 'X-Real-Ip': '136.152.142.36'})
Traceback (most recent call last):
  File "/opt/accessors/server/lib/python3.4/site-packages/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "./accessor_host.py", line 1546, in post
    return self.compile(name, self.request.body.decode('utf-8'))
  File "./accessor_host.py", line 1533, in compile
    for e in err['extra']:
KeyError: 'extra'
```

**Comment by bradjc** [comment]
what it says not broken:

```
Attempt to send to '/onoff/Power', but that is not a created port or a port in a provided interface
```
